project:
  type: website

website:
  title: "DIE-BG"
  navbar:
    pinned: true
    tools:
      - icon: github
        menu:
          - text: Organization
            href: https://github.com/DIE-BG
    left:
      - text: Home
        href: index.qmd
      - sidebar:hefm 
      - sidebar:btima     
      #- sidebar:projects
      #- text: "Team"
        #href: team.qmd
      #- about.qmd

  sidebar:
    - id: hefm
      title: "HEFM"
      style: "docked"
      search: true
      contents:
        - href: hefm/index.qmd
          text: "HEFM"
        - section: "Results"
          contents:
            - section: "SVAR50-4B"
              contents:
                - text: "Index"
                  href: hefm/results/SVAR50_4B/index.qmd
                - text: "Variable Final Estimation Date"
                  href: hefm/results/SVAR50_4B/SVAR50_4B_forecast_OS_finalEstPeriod/index.qmd
                - text: "Variable Initial Estimation Date (IS)"
                  href: hefm/results/SVAR50_4B/SVAR50_forecast_IS_initialEstPeriod/index.qmd
                - text: "Variable Initial Estimation Date (OS)"
                  href: hefm/results/SVAR50_4B/SVAR50_forecast_OS_initialEstPeriod/index.qmd
                - text: "Variable Sample Size"
                  href: hefm/results/SVAR50_4B/SVAR50_4B_HV/index.qmd
            - section: "SVAR50-AR1"
              contents: 
                - text: "Comparaci칩n del SVAR50-4B y el SVAR50-AR1"
                  href: hefm/results/SVAR50_AR1/SVAR_AR1_OS_doc.qmd
            - section: "SVAR51"
              contents:
                - text: "Acercamiento QPM con el SVAR51"
                  href: hefm/results/SVAR51/SVAR51.qmd
            - section: "SVAR52"
              contents: 
                - text: "Comparaci칩n del SVAR50-4B y el SVAR52"
                  href: hefm/results/SVAR52/SVAR52_doc.qmd
            - section: "SVAR53"
              contents:
                - text: "Index"
                  href: hefm/results/SVAR53/index.qmd  
                - text: "Calibraci칩n de hiperpar치metros"
                  href: hefm/results/SVAR53/Lambdas/SVAR53_lambdas_doc.qmd
    - id: btima
      title: "BTIMA"
      style: "docked"
      search: true
      contents:
        - href: BTIMA/index.qmd
          text: "BTIMA"
        - section: "BTIMA Extension"
          contents:
            - text: "Methodology"
              href: BTIMA/BTIMA_extension_math.qmd
            - text: "Matching and calibration"
              href: BTIMA/doc_matching_calibration.qmd
execute: 
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
    css: assets/css/styles.css
    toc: true