---
title: Ejercicio de simulación
subtitle: Exploración de valores para $h$
lang: es
bibliography: reference.bib
format: 
    revealjs: 
        smaller: true
        progress: true
        controls: true
        controls-back-arrows: faded
        center: true
nocite: |
    @*
---

El siguiente ejercicio de simulación se basa en los propuestos por @burman1994cross para la determinación de un valor $h$ en los ejercicios de validación cruzada. 

---
 
Aunque los ejercicios de validación cruzada propuestos por los autores exploran diferentes formas de dependencia temporal y múltiples especificaciones de autocorrelación, nos planteamos las siguientes preguntas:

- ¿En un contexto multivariado, los valores de $h$ recomendados son capaces de generar una buena estimación del MSE a horizonte uno?
- ¿Utilizando los valores recomendados de $h$ es posible estimar correctamente el MSE para horizontes mayores a uno?
- ¿Cómo se ve afectada la estimación del MSE con diferentes valores de $h$ si el término de error no es Gaussiano?
- ¿Los valores recomendados de $h$ son compatibles con el esquema de validación cruzada usado en la HEFM?

---

Para explorar estas preguntas, se plantea un ejercicios de simulación con las siguientes características:

---

Todos los ejercicios de simulación utilizarán como base la estructura del VAR reducido del SVAR50-4B; es decir, los coeficientes $C$ y $A_1$ del modelo poblacional provendrán de la estimación del SVAR50-4B en la muestra completa de los datos observados para Guatemala.

$$
y_t = C + A_1 y_{t-1} + u_t
$${#eq-svar504b}

En lugar de suponer un proceso gaussiano para $u_t$, se propone utilizar una distribución empírica derivada de los residuos de la estimación del SVAR50-4B; es decir,

$$
u_t \sim F_{\hat{u}}
$$

---

Una muestra aleatoria $\mathcal{Y} = \lbrace y_1, \dots, y_t, \dots, y_T \rbrace$ se utilizará para computar el MSE de validación cruzada bajo el esquema de la HEFM.^[Este esquema de validación cruzada no es exactamente el propuesto por @burman1994cross.]

El tamaño de la muestra $\mathcal{Y}$ será uno de los componentes que variarán en los ejercicios de simulación, ya que se busca explorar el efecto que tiene el tamaño muestral en la estimación del MSE real.

---

Nos interesa estudiar el MSE de validación cruzada para horizontes de pronóstico de hasta 8 periodos; esto implica que el bloque $v$ del esquema de validación será igual a 8.

Denotamos el MSE de validación cruzada según el enfoque HEFM como:^[La fórmula explícita de esta magnitud forma parte del esfuerzo actual en la documentación del HEFM.]

$$
CV_{HEFM}(h,v,j)
$$

donde:

- $h$ es el tamaño del bloque de descarte,  
- $v$ es el horizonte de pronóstico máximo a evaluar, que se define como 8,  
- $j$ es el horizonte de pronóstico al que corresponde la magnitud calculada. Este valor debe cumplir siempre $j \leq v$.

---

El MSE real al estimar sobre la muestra completa $\mathcal{Y}$ solo puede calcularse si se dispone de una muestra independiente $\tilde{\mathcal{Y}} = \lbrace \tilde{y}_{0}, \tilde{y}_2, \dots, \tilde{y}_{v} \rbrace$, distinta a la utilizada para la estimación.

Este MSE se define como:

$$
E \left[ PE(j) \right] = E \left[ 
    \left( 
        \tilde{y}_{j} 
        - \sum_{i=1}^j \hat{A}_1^{i-1} \hat{C} - \hat{A}_1^j \tilde{y}_0
    \right)^2
\right]
$$

Esta magnitud presenta dos fuentes de aleatoriedad: una proveniente de la muestra de estimación $\mathcal{Y}$ y otra de la muestra utilizada para medir el error, $\tilde{\mathcal{Y}}$.

Para poder aproximarla mediante simulación, es necesario aplicar la ley de la esperanza iterada:

$$
E \left[ PE(j) \right] 
=
E \left[ 
    E \left[
        PE(j) \mid \mathcal{Y}
    \right]
\right]
= 
E \left[ 
    E \left[
        \left( 
            \tilde{y}_{j} 
            - \sum_{i=1}^j \hat{A}_1^{i-1} \hat{C} - \hat{A}_1^j \tilde{y}_0
        \right)^2
        \mid
        \mathcal{Y}
    \right]
\right]
$$

Recordemos que $j$ representa el horizonte de pronóstico y $j = 1, 2, \dots, v$.

---

Los pasos para realizar la simulación son los siguientes:

0. Elegir el tamaño de muestra $T$ para la simulación.

1. Simular 10,000 realizaciones de la muestra aleatoria $\mathcal{Y}$, indexada por $m$ y denotada como $\lbrace y_1^{(m)}, \dots, y_T^{(m)} \rbrace$.

2. Simular 10,000 realizaciones de la muestra aleatoria $\tilde{\mathcal{Y}}$, indexada por $w$ y denotada como $\lbrace \tilde{y}_{0}^{(w)}, \dots, \tilde{y}_{v}^{(w)} \rbrace$.

Estas simulaciones deben seguir el proceso definido por @eq-svar504b.

---

3. Se estima el valor esperado del MSE por validación cruzada a la HEFM, $E\left[CV_{HEFM}(h,v,j)\right]$.

$$
\hat{E}\left[CV_{HEFM}(h,v,j)\right] 
=
\dfrac{1}{10,000} {
    \sum_{i = 1}^{n} {
        CV_{HEFM}^{(m)}(h,v,j)
    }
}
$$

Esta magnitud de computaría $h \times v$ veces, una por cada combinación de $h$ y $j$.

---

4. Se estima el valor esperado del MSE real, $E\left[PE(j)\right]$.

$$
\hat{E}\left[PE(j)\right]
=
\dfrac{1}{100 \times 10^6} \sum_{m=1}^{10,000}{ 
    \sum_{w=1}^{10,000} {
        \left( 
            \tilde{y}_{j}^{(w)} 
            - \sum_{i=1}^j \hat{A}_1^{(m) i-1} \hat{C}^{(m)} - \hat{A}_1^{(m) j} \tilde{y}_0^{(w)}
        \right)^2
    }
}
$$

Esta magnitud se computaría $v$ veces.

---

Finalmente, se comparan las distribuciones de $\hat{E}\left[PE(j)\right]$ y $\hat{E}\left[CV_{HEFM}(h,v,j)\right]$ con el fin de:

- Diagnosticar posibles sesgos en la estimación del MSE real fuera de muestra.  
- Seleccionar el valor de $h$ que ofrezca la estimación más eficiente del MSE fuera de muestra.

## Referencias

::: {#ref}
:::