---
title: "All SVAR50-4B Results"

frame_height: "400px"
frame_width: "100%"

SVAR50_4B: 
    dir: "/hefm/results/SVAR50_4B"
    name: "SVAR50-4B"
    decks: 
        - dir: "SVAR50_4B_forecast_OS_finalEstPeriod"
          filename: "SVAR50_4B_forecast_OS_finalEstPeriod"
          title: "Variable Final Estimation Date"
        - dir: "SVAR50_forecast_IS_initialEstPeriod"
          filename: "forecast_IS_initialEstPeriod"
          title: "Variable Initial Estimation Date (IS)"
        - dir: "SVAR50_forecast_OS_initialEstPeriod"
          filename: "forecast_OS_initialEstPeriod"
          title: "Variable Initial Estimation Date (OS)"
        - dir: "SVAR50_4B_HV"
          filename: "SVAR50_4B_HV"
          title: "Variable Sample Size"
---

- [**Variable Final Estimation Date**](/hefm/results/SVAR50_4B/SVAR50_4B_forecast_OS_finalEstPeriod/index.qmd):
This exercise examines the impact on RMSE of adding new observations to the estimation sample.
The effect is evaluated both in-sample and out-of-sample, using fixed and rolling validation sets.

- [**Variable Initial Estimation Date (IS)**](/hefm/results/SVAR50_4B/SVAR50_forecast_IS_initialEstPeriod/index.qmd):
This exercise examines the impact on RMSE of excluding earlier observations from the estimation sample.
The effect is measured *in-sample*.

- [**Variable Initial Estimation Date (OS)**](/hefm/results/SVAR50_4B/SVAR50_forecast_OS_initialEstPeriod/index.qmd):
This exercise examines the impact on RMSE of excluding earlier observations from the estimation sample.
The effect is measured *out-of-sample*.

- [**Variable Sample Size**](/hefm/results/SVAR50_4B/SVAR50_4B_HV/index.qmd):
This exercise explores the impact of sample size on RMSE.
An *HV*-type evaluation scheme is used to isolate the effect of autocorrelation on RMSE.